yolo_model:

  config_file:
    name: yolo_kitti.cfg #yolo_bdd_c1.cfg # yolo-obj.cfg  # yolov3-bdd.cfg
  weight_file:
    name: yolo_kitti_21500.weights #yolo_bdd_c1_165300.weights #yolov_ugv.backup # yolo-obj_7100.weights #   #yolov3-bdd.weights
  threshold:
    value: 0.3
  detection_classes:
    names:
      - car
      - pedestrian
